// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the different types of cardio workouts you can do.
 */
export type CardioExercise = "Running" | "Swimming" | "Cycling";
