[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[dependencies]
tiberius = "0.12.3"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["full"] }
